### ISSUE TITLE
Can not import github_binary_upload

### ISSUE THREAD

**Issue by faniAhmed** [sciapp/github-binary-upload#3]
I can not import the module gives me error file not found. I dont know why this error is showing up.
`
### Traceback (most recent call last):

  File "c:\Users\Farhan Ahmed\Desktop\code\f1\main.py", line 1, in <module>
    from github_binary_upload import publish_release_from_tag
  File "C:\Users\Farhan Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\github_binary_upload.py", line 18, in <module>
    from yacl import setup_colored_stderr_logging
  File "C:\Users\Farhan Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\yacl.py", line 271, in <module>
    class ColoredFormatter(logging.Formatter):
  File "C:\Users\Farhan Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\yacl.py", line 273, in ColoredFormatter
    "funcName": TerminalColorCodes.blue,
  File "C:\Users\Farhan Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\yacl.py", line 160, in blue
    cls._init_terminal_codes()
  File "C:\Users\Farhan Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\yacl.py", line 107, in _init_terminal_codes
    has_terminal_color = cls.has_terminal_color()
  File "C:\Users\Farhan Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\yacl.py", line 129, in has_terminal_color
    or (is_stderr_tty() and int(cls._query_terminfo_database("colors")) >= 8)
  File "C:\Users\Farhan Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\yacl.py", line 123, in _query_terminfo_database
    return str(subprocess.check_output(["tput"] + capname.split(), universal_newlines=True))
  File "C:\Users\Farhan Ahmed\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\Farhan Ahmed\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\Farhan Ahmed\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Farhan Ahmed\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1435, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
`
![image](https://user-images.githubusercontent.com/89826402/168792389-2ab8edc9-6820-4bb7-8b36-cf332b96396d.png)

**Comment by IngoMeyer441** [comment]
Thanks for your bug report. The error is raised by the `yacl` package which is also maintained by me. The error is fixed in the latest `yacl` release (v0.4.4). Please upgrade it to make `github_binary_upload` work, usually with:
```bash
pip install -U yacl
```
Also see <https://github.com/IngoMeyer441/yacl/issues/1> for the corresponding `yacl` issue.

**Comment by faniAhmed** [comment]
Thanks it worked
